### PR TITLE
Switch to Github Actions and prepare for 2.4 release

### PR DESCRIPTION
**Pull request by Techcable**
The GH actions workflow are mostly copied from slog-rs

Changes:
1. We have a different MSRV
2. Don't need to test different feature combos
3. clippy is required to succeed

Also
- Explicitly document Minimum Supported Rust Version
- Update `CHANGELOG.md` with all the recent changes

After we do all this we should probably publish a new release.

I think we'll probably need to bump the minor version (2.3 -> 2.4) because of the MSRV version bump.

### CODE REVIEW

**Comment by Techcable** [comment]
I'm going to convert this to a draft, because we should release `slog-json` first....

So effectively this is blocked on `slog-json` release

TODO:
- [ ] Release new version of slog-json
   - [x] Convert slog-json to use Github Actions  
   - [ ] Accept PR slog-rs/json#29

**Comment by Techcable** [comment]
**WARNING:** This will not compile until we publish `slog-json` release `2.6` (you accept PR slog-rs/json#29)

**Comment by Techcable** [comment]
Okay this is ready to go!

**Comment by Techcable** [comment]
Shoot. Sorry about the ping. I can't merge this myself 😆

**Review by dpc — APPROVED** [review]

**Comment by dpc** [comment]
It's OK. Keep pinging me whenever you're blocked on anything. Thanks a lot!

**Comment by Techcable** [comment]
@dpc Unfortunately I am not a co-owner of `slog-bunyan` on crates.io. This means I cannot publish the 2.4.0 release  😦

**Comment by dpc** [comment]
@Techcable Now?

**Comment by Techcable** [comment]
> @Techcable Now?

Yes. It works now :)

**Pull request merged**
